# Generated by Django 3.1.4 on 2021-04-10 12:10

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.TextField(max_length=300)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.ImageField(upload_to='media/category/images')),
                ('city', models.CharField(blank=True, choices=[('New York', 'New York'), ('Santa Monica', 'Santa Monica')], max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/client/images')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='forgot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sub_name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='media/portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='registartion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('confirm_password', models.CharField(max_length=12)),
                ('bday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('o', 'other')], max_length=1)),
                ('profile', models.CharField(choices=[('B', 'Businessman'), ('C', 'Client')], max_length=1)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/slider/images')),
            ],
        ),
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/team/images')),
                ('twitter', models.URLField(max_length=250)),
                ('facebook', models.URLField(max_length=250)),
                ('instagram', models.URLField(max_length=250)),
                ('linkedin', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('2', 'Vehical'), ('3', 'Electronics_applices'), ('4', 'Fashion'), ('5', 'Kids'), ('6', 'Pets'), ('7', 'Real_estate')], default='1', max_length=20)),
                ('photo', models.ImageField(upload_to='media/category/images')),
                ('sub_category', models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, to='app.sub')),
            ],
        ),
    ]
