# Generated by Django 3.2 on 2021-05-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businessdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_Shortdetail', models.CharField(max_length=500)),
                ('Business_Detail', models.CharField(max_length=500)),
                ('Business_Date', models.DateTimeField()),
                ('Business_Brand', models.CharField(max_length=30)),
                ('Business_Brandweb', models.URLField(max_length=2000)),
                ('Business_Mobile', models.CharField(max_length=15)),
                ('Business_Email', models.CharField(max_length=50)),
                ('Business_Turnover', models.CharField(max_length=15)),
                ('Business_Sate', models.CharField(choices=[('GUJRAT', 'GUJRAT'), ('DELHI', 'DELHI'), ('Maharashtra', 'Maharashtra'), ('PANJAB', 'PANJAB')], default='1', max_length=60)),
                ('Business_Country', models.CharField(choices=[('INDIA', 'INDIA'), ('US', 'US'), ('CANADA', 'CANADA'), ('RUSSIA', 'RUSSIA')], default='1', max_length=60)),
                ('Business_Address', models.TextField(max_length=500)),
                ('Business_Location', models.URLField(max_length=2000)),
                ('Business_Type', models.CharField(choices=[('Technology', 'Technology'), ('Agriculture', 'Agriculture'), ('Architecture', 'Architecture'), ('Book', 'Book'), ('Consultants', 'Consultants'), ('Catarers', 'Catarers'), ('Carpenters', 'Carpenters'), ('Electronics_applices', 'Electronics_applices'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Furnitures', 'Furnitures'), ('Kids', 'Kids'), ('Pets', 'Pets'), ('Retail', 'Retail'), ('Real_estate', 'Real_estate'), ('Sell Cosmetic', 'Sell Cosmetic'), ('Vehical', 'Vehical')], default='1', max_length=50)),
                ('Business_Marketplace', models.CharField(choices=[('Monopolic', 'Monopolic'), ('Non-Monopolic', 'Non-Monopolic')], default='1', max_length=50)),
                ('Business_Features', models.CharField(max_length=800)),
                ('Business_Photo', models.ImageField(upload_to='media/Business/category/images')),
            ],
        ),
        migrations.CreateModel(
            name='Businessslide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ImageField(upload_to='media/Businessslide/images')),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/client/images')),
                ('Web', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Client_email', models.CharField(max_length=50)),
                ('Client_message', models.CharField(max_length=500)),
                ('Client_Date', models.DateTimeField()),
                ('Client_Mobile', models.CharField(max_length=15)),
                ('Client_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_name', models.CharField(max_length=20)),
                ('Loan_Type', models.CharField(max_length=30)),
                ('Interest_Rate', models.CharField(max_length=50)),
                ('Loan_Amount', models.CharField(max_length=20)),
                ('Re_payment_Period', models.CharField(max_length=30)),
                ('Address', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sub_name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='media/portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='profile1.png', null=True, upload_to='media/profilephoto/images')),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=264)),
                ('c_password', models.CharField(max_length=264)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('o', 'other')], default='FEMALE', max_length=1)),
                ('profile', models.CharField(choices=[('B', 'Businessman'), ('C', 'Client')], default='Businessman', max_length=1)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ShareStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('story', models.TextField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/slider/images')),
            ],
        ),
        migrations.CreateModel(
            name='sub_portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sub_name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/sub_portfolio/tech_portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/team/images')),
                ('twitter', models.URLField(max_length=250)),
                ('facebook', models.URLField(max_length=250)),
                ('instagram', models.URLField(max_length=250)),
                ('linkedin', models.URLField(max_length=250)),
            ],
        ),
    ]
