# Generated by Django 3.1.4 on 2021-04-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businessdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_Shortdetail', models.CharField(max_length=500)),
                ('Business_Detail', models.CharField(max_length=500)),
                ('Business_Date', models.DateTimeField()),
                ('Business_Brand', models.CharField(max_length=30)),
                ('Business_Brandweb', models.URLField(max_length=2000)),
                ('Business_Mobile', models.CharField(max_length=15)),
                ('Business_Email', models.CharField(max_length=50)),
                ('Business_Turnover', models.CharField(max_length=15)),
                ('Business_Type', models.CharField(choices=[('Technology', 'Technology'), ('Agriculture', 'Agriculture'), ('Architecture', 'Architecture'), ('Book', 'Book'), ('Consultants', 'Consultants'), ('Catarers', 'Catarers'), ('Carpenters', 'Carpenters'), ('Electronics_applices', 'Electronics_applices'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Furnitures', 'Furnitures'), ('Kids', 'Kids'), ('Pets', 'Pets'), ('Retail', 'Retail'), ('Real_estate', 'Real_estate'), ('Sell Cosmetic', 'Sell Cosmetic'), ('Vehical', 'Vehical')], default='1', max_length=50)),
                ('Business_Marketplace', models.CharField(choices=[('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('PRO', 'PRO')], default='1', max_length=50)),
                ('Business_Features', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Businessslide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ImageField(upload_to='media/Businessslide/images')),
            ],
        ),
        migrations.CreateModel(
            name='cat_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.TextField(max_length=300)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.ImageField(upload_to='media/category/images')),
                ('city', models.CharField(blank=True, choices=[('New York', 'New York'), ('Santa Monica', 'Santa Monica')], max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Agriculture', 'Agriculture'), ('Architecture', 'Architecture'), ('Book', 'Book'), ('Consultants', 'Consultants'), ('Catarers', 'Catarers'), ('Carpenters', 'Carpenters'), ('Electronics_applices', 'Electronics_applices'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Furnitures', 'Furnitures'), ('Kids', 'Kids'), ('Pets', 'Pets'), ('Retail', 'Retail'), ('Real_estate', 'Real_estate'), ('Sell Cosmetic', 'Sell Cosmetic'), ('Vehical', 'Vehical')], default='1', max_length=50)),
                ('sub_category', models.CharField(choices=[('Technology', (('Sofware', 'Sofware'), ('Harware', 'Harware'), ('Web Development', 'Web Development'), ('Computer Repairing', 'Computer Repairing'), ('Digital Iteam Selling', 'Digital Iteam Selling'))), ('Architecture', (('Architectural Designer', 'Architectural Designer'), ('Urban Plan', 'Urban Plan'), ('Wooden Architecture', 'Wooden Architecture'))), ('Agriculture', (('Farming Business', 'Farming Business'), ('Equipment Resource', 'Equipment Resource'), ('Machinery Resource', 'Machinery Resource'), ('Products Storage', 'Products Storage'), ('Prodcut Seller', 'Prodcut Seller'))), ('Book', (('Special markets booksellers', 'Special markets booksellers'), ('Big box stores', 'Big box stores'), ('Price clubs', 'Price clubs'))), ('Consultants', (('Lowyer Advice', 'Lowyer Advice'), ('CA', 'CA'), ('Valuers', 'Valuers'))), ('Catarers', (('Birthday/Event/Function party', 'Birthday/Event/Function party'), ('Wedding Catarers', 'Wedding Catarers'))), ('Carpenters', (('Home Care', 'Home Care'), ('Wood Work', 'Wood Work'), ('Fabrication', 'Fabrication'))), ('Electronics_applices', (('Computers & accessories', 'Computers & accessories'), ('Mobile', 'Mobile'), ('Tv - video - audio', 'Tv - video - audio'), ('Cameras & accessories', 'Cameras & accessories'), ('Games & Entertainment', 'Games & Entertainment'), ('Fridge - AC - Washing Machine', 'Fridge - AC - Washing Machine'), ('Kitchen', 'Kitchen'))), ('Education', (('Classes', 'Classes'), ('Coaching', 'Coaching'), ('Institute', 'Institute'))), ('Fashion', (('Clothes', 'Clothes'), ('Footwear', 'Footwear'), ('Accessories', 'Accessories'))), ('Furnitures', (('Sofa & Dining ', 'Sofa & Dining '), ('Beds & Wardrobes', 'Beds & Wardrobes'), ('Home Decor & Garden', 'Home Decor & Garden'), ('Other Household Items', 'Other Household Items'))), ('Kids', (('Furniture And Toys', 'Furniture And Toys'), ('Prams & Walkers', 'Prams & Walkers'), ('Accessories', 'Accessories'))), ('Pets', (('Dogs', 'Dogs'), ('Aquariums', 'Aquariums'), ('Pet Food & Accessories', 'Pet Food & Accessories'), ('Other Pets', 'Other Pets'))), ('Retail', (('Grocery Store', 'Grocery Store'), ('Convenience Store', 'Convenience Store'), ('Hyper Market', 'Hyper Market'))), ('Real_estate', (('Residential', 'Residential'), ('Industrial', 'Industrial'), ('Commercial', 'Commercial'))), ('Sell Cosmetic', (('Beauty Parlours', 'Beauty Parlours'), ('Salon', 'Salon'), ('Spa', 'Spa'))), ('Vehical', (('Hiring', 'Hiring'), ('Commercial Vehicles', 'Commercial Vehicles'), ('Other Vehicles', 'Other Vehicles'), ('Spare Parts', 'Spare Parts')))], default='11', max_length=50)),
                ('photo', models.ImageField(upload_to='media/category/images')),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/client/images')),
                ('Web', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Client_email', models.CharField(max_length=50)),
                ('Client_message', models.CharField(max_length=500)),
                ('Client_Date', models.DateTimeField()),
                ('Client_Mobile', models.CharField(max_length=15)),
                ('Client_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=300)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='forgot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_name', models.CharField(max_length=20)),
                ('Loan_Type', models.CharField(max_length=30)),
                ('Interest_Rate', models.CharField(max_length=50)),
                ('Loan_Amount', models.CharField(max_length=20)),
                ('Re_payment_Period', models.CharField(max_length=30)),
                ('Address', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sub_name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='media/portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('o', 'other')], max_length=1)),
                ('profile', models.CharField(choices=[('B', 'Businessman'), ('C', 'Client')], max_length=1)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/slider/images')),
            ],
        ),
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sub_portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sub_name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/sub_portfolio/tech_portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/team/images')),
                ('twitter', models.URLField(max_length=250)),
                ('facebook', models.URLField(max_length=250)),
                ('instagram', models.URLField(max_length=250)),
                ('linkedin', models.URLField(max_length=250)),
            ],
        ),
    ]
