# Generated by Django 3.2 on 2021-05-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdetail',
            old_name='Business_Sate',
            new_name='Business_State',
        ),
    ]
