# Generated by Django 3.1.4 on 2021-04-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Businessslide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ImageField(upload_to='media/Businessslide/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='businessdetail',
            name='Business_Slid',
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='Business_Brandweb',
            field=models.URLField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
