# Generated by Django 3.1.4 on 2021-04-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.CharField(choices=[('Technology', (('11', 'Sofware'), ('12', 'Harware'), ('13', 'Web Development'), ('13', 'Computer Repairing'))), ('Vehical', (('21', 'Hiring'), ('22', 'Commercial Vehicles'), ('22', 'Other Vehicles'), ('22', 'Spare Parts'))), ('Electronics_applices', (('31', 'Computers & accessories'), ('32', 'Mobile'), ('32', 'Tv - video - audio'), ('32', 'Cameras & accessories'), ('32', 'Games & Entertainment'), ('32', 'Fridge - AC - Washing Machine'), ('32', 'Kitchen'))), ('Fashion', (('41', 'Clothes'), ('42', 'Footwear'), ('42', 'Accessories '))), ('Retail', (('51', 'Clothes'), ('52', 'Footwear'), ('52', 'Accessories '))), ('Furnitures', (('61', 'Sofa & Dining '), ('62', 'Beds & Wardrobes '), ('62', 'Home Decor & Garden'), ('62', 'Other Household Items'))), ('Kids', (('71', 'Furniture And Toys'), ('72', 'Prams & Walkers'), ('72', 'Accessories'))), ('Pets', (('81', 'Dogs'), ('82', 'Aquariums'), ('82', 'Pet Food & Accessories'), ('82', 'Other Pets'))), ('Real_estate', (('91', 'Groceries'), ('92', 'Restaurants')))], default='11', max_length=20),
        ),
    ]
