# Generated by Django 3.2 on 2021-05-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_business_sate_businessdetail_business_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
