# Generated by Django 3.1.4 on 2021-04-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210410_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Agriculture', 'Agriculture'), ('Architecture', 'Architecture'), ('Book', 'Book'), ('Consultants', 'Consultants'), ('Catarers', 'Catarers'), ('Carpenters', 'Carpenters'), ('Electronics_applices', 'Electronics_applices'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Furnitures', 'Furnitures'), ('Kids', 'Kids'), ('Pets', 'Pets'), ('Retail', 'Retail'), ('Real_estate', 'Real_estate'), ('Sell Cosmetic', 'Sell Cosmetic'), ('Vehical', 'Vehical')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.CharField(choices=[('Technology', (('11', 'Sofware'), ('12', 'Harware'), ('13', 'Web Development'), ('13', 'Computer Repairing'), ('13', 'Digital Iteam Selling'))), ('Architecture', (('21', 'Architectural Designer'), ('22', 'Urban Plan'), ('23', 'Wooden Architecture'))), ('Agriculture', (('31', 'Farming Business'), ('32', 'Equipment Resource'), ('33', 'Machinery Resource'), ('34', 'Products Storage'), ('35', 'Prodcut Seller'))), ('Book', (('41', 'Special markets booksellers'), ('42', 'Big box stores'), ('43', 'Price clubs'))), ('Consultants', (('51', 'Lowyer Advice'), ('52', 'CA'), ('53', 'Valuers'))), ('Catarers', (('61', 'Birthday/Event/Function party'), ('62', 'Wedding Catarers'))), ('Carpenters', (('71', 'Home Care'), ('72', 'Wood Work'), ('73', 'Fabrication'))), ('Electronics_applices', (('81', 'Computers & accessories'), ('82', 'Mobile'), ('83', 'Tv - video - audio'), ('84', 'Cameras & accessories'), ('85', 'Games & Entertainment'), ('86', 'Fridge - AC - Washing Machine'), ('87', 'Kitchen'))), ('Education', (('91', 'Classes'), ('92', 'Coaching'), ('93', 'Institute'))), ('Fashion', (('101', 'Clothes'), ('102', 'Footwear'), ('103', 'Accessories '))), ('Furnitures', (('111', 'Sofa & Dining '), ('112', 'Beds & Wardrobes '), ('113', 'Home Decor & Garden'), ('114', 'Other Household Items'))), ('Kids', (('121', 'Furniture And Toys'), ('122', 'Prams & Walkers'), ('123', 'Accessories'))), ('Pets', (('131', 'Dogs'), ('132', 'Aquariums'), ('133', 'Pet Food & Accessories'), ('134', 'Other Pets'))), ('Retail', (('141', 'Grocery Store'), ('142', 'Convenience Store'), ('143', 'Hyper Market'))), ('Real_estate', (('151', 'Residential'), ('152', ' Industrial'), ('153', ' Commercial'))), ('Sell Cosmetic', (('161', 'Beauty Parlours'), ('162', 'Salon'), ('163', 'Spa'))), ('Vehical', (('171', 'Hiring'), ('172', 'Commercial Vehicles'), ('173', 'Other Vehicles'), ('174', 'Spare Parts')))], default='11', max_length=20),
        ),
    ]
