# Generated by Django 3.1.4 on 2021-04-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210411_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/sub_portfolio/images')),
            ],
        ),
    ]
