# Generated by Django 3.2.2 on 2021-05-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_reg_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='Business_Country',
            field=models.CharField(choices=[('INDIA', 'INDIA'), ('US', 'US'), ('CANADA', 'CANADA'), ('RUSSIA', 'RUSSIA')], default='INDIA', max_length=60),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='Business_Marketplace',
            field=models.CharField(choices=[('Monopolic', 'Monopolic'), ('Non-Monopolic', 'Non-Monopolic')], default='Monopolic', max_length=50),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='Business_State',
            field=models.CharField(choices=[('GUJRAT', 'GUJRAT'), ('DELHI', 'DELHI'), ('Maharashtra', 'Maharashtra'), ('PANJAB', 'PANJAB')], default='GUJRAT', max_length=60),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='Business_Type',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Agriculture', 'Agriculture'), ('Architecture', 'Architecture'), ('Book', 'Book'), ('Consultants', 'Consultants'), ('Catarers', 'Catarers'), ('Carpenters', 'Carpenters'), ('Electronics_applices', 'Electronics_applices'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Furnitures', 'Furnitures'), ('Kids', 'Kids'), ('Pets', 'Pets'), ('Retail', 'Retail'), ('Real_estate', 'Real_estate'), ('Sell Cosmetic', 'Sell Cosmetic'), ('Vehical', 'Vehical')], default='Technology', max_length=50),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='businessslide',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reg',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reg',
            name='profile',
            field=models.CharField(choices=[('Businessman', 'Businessman'), ('Client', 'Client')], default='Businessman', max_length=20),
        ),
        migrations.AlterField(
            model_name='sharestory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sub_portfolio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
