# Generated by Django 3.1.4 on 2021-04-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210422_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
        migrations.AddField(
            model_name='contactus',
            name='mobile',
            field=models.IntegerField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
