# Generated by Django 3.1.4 on 2021-04-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210422_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
