# Generated by Django 3.1.4 on 2021-04-11 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sub_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_portfolio',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
