# Generated by Django 3.1.4 on 2021-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sub_portfolio_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='auto_portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/sub_portfolio/auto_portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='book_portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/sub_portfolio/book_portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='furniture_portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/sub_portfolio/real_portfolio/furniture_portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='real_portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/sub_portfolio/real_portfolio/real_portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='retail_portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/sub_portfolio/retail_portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='tech_portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='media/sub_portfolio/tech_portfolio/images')),
            ],
        ),
        migrations.DeleteModel(
            name='sub_portfolio',
        ),
    ]
