# Generated by Django 3.1.4 on 2021-04-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210422_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
