# Generated by Django 3.1.4 on 2021-04-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210411_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Request',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('client_name', models.CharField(max_length=12)),
                ('Desc', models.TextField(max_length=300)),
            ],
        ),
    ]
