# Generated by Django 3.1.4 on 2021-03-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210328_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registartion',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
