# Generated by Django 3.1.4 on 2021-03-28 08:29

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210328_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registartion',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
