# Generated by Django 3.1.4 on 2021-04-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210422_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
