# Generated by Django 3.1.4 on 2021-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_client_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech_portfolio',
            name='link',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
