# Generated by Django 3.1.4 on 2021-03-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210328_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registartion',
            old_name='birth_date',
            new_name='bday',
        ),
    ]
