# Generated by Django 3.1.4 on 2021-04-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210422_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='Business_Shortdetail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
