# Generated by Django 3.1.4 on 2021-04-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tech_portfolio_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registartion',
            old_name='bday',
            new_name='birthdate',
        ),
        migrations.RemoveField(
            model_name='registartion',
            name='confirm_password',
        ),
    ]
