# Generated by Django 3.1.4 on 2021-04-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210423_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='Business_Detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='Business_Features',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
