# Generated by Django 3.1.4 on 2021-04-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210412_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech_portfolio',
            name='link',
        ),
        migrations.AddField(
            model_name='tech_portfolio',
            name='sub_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
