# Generated by Django 3.1.4 on 2021-04-22 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210423_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='Business_Detail',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='Business_Features',
            field=models.CharField(default=1, max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='Business_Shortdetail',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
