# Generated by Django 3.1.4 on 2021-04-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210413_0116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auto_portfolio',
        ),
        migrations.DeleteModel(
            name='book_portfolio',
        ),
        migrations.DeleteModel(
            name='furniture_portfolio',
        ),
        migrations.DeleteModel(
            name='real_portfolio',
        ),
        migrations.DeleteModel(
            name='retail_portfolio',
        ),
    ]
