# Generated by Django 3.1.4 on 2021-03-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_slider_team'),
        ('app', '0010_team'),
    ]

    operations = [
    ]
