# Generated by Django 3.1.4 on 2021-04-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210423_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='c_password',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
