# Generated by Django 3.1.4 on 2021-04-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210413_0220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tech_portfolio',
            new_name='sub_portfolio',
        ),
    ]
