# Generated by Django 3.1.4 on 2021-04-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210413_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_name', models.CharField(max_length=20)),
                ('Loan_Type', models.CharField(max_length=20)),
                ('Interest_Rate', models.CharField(max_length=10)),
                ('Loan_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Re_payment_Period', models.DurationField()),
                ('Address', models.URLField(max_length=2000)),
            ],
        ),
    ]
