# Generated by Django 3.1.4 on 2021-04-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_reg_c_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='photo',
            field=models.ImageField(default=1, upload_to='media/profilephoto/images'),
            preserve_default=False,
        ),
    ]
