# Generated by Django 3.1.4 on 2021-04-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_reg_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='c_password',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='reg',
            name='password',
            field=models.CharField(max_length=264),
        ),
    ]
