# Generated by Django 3.1.4 on 2021-04-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='Interest_Rate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='loan',
            name='Loan_Amount',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='Loan_Type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='Re_payment_Period',
            field=models.CharField(max_length=30),
        ),
    ]
