# Generated by Django 3.1.4 on 2021-04-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210413_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Web',
            field=models.URLField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
